### ISSUE TITLE
[Architecture]: Initial Carbon for AI Architecture setup (Phase 1)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ai#7]
### User story

> As a `[user role below]`:

User of Carbon for AI

> I need to:

Have available a storybook, npm, and CDN artifacts in the Carbon for AI library

> so that I can:

Integrate AI experiences into my IBM Product/Application

### Additional information

- Approach will be an open-source library under the Apache 2.0 license
- Library will utilize Carbon Web Components, and will be built as Web Components
- Will use the `@carbon/ai` package name
   - Should determine if we can identify and publish experimental components under the `@carbon-labs/ai` package name
- All components for the initial phase will be published as experimental
- Should publish components in a way that classes and templates can be exported separately to allow extensibility for teams that wish to define their own custom elements in addition to having custom elements be automatically defined
- Example Github Actions for CDN publishing:
  - https://github.com/IBM-Design/design-website/actions/workflows/deploy.yml
- CDN publishing will utilize the same Content Object Storage bucket used by Carbon Web Components, and published on IBM Akamai servers
- Considering the following technologies
  - Storybook v7, Vite, Lit v3, rollup, pnpm
- Environments:
  - Production: Manual deployment based on tag (COS hosted)
  - Stage: Manual deployment based on tag (off release branches) (COS hosted)
  - Canary: Automatic deployments based off `main` branch (Netlify hosted)
  - Deploy previews: Automatic deployments in pull requests (Netlify hosted)

```[tasklist]
### Tasks
- [x] Storybook environment setup for production
- [x] Storybook environment setup for staging
- [x] Storybook environment setup for canary
- [x] Storybook environment setup for deploy previews
- [x] CI/CD pipelines set up for npm publishing (semver tagging and publishing)
- [x] CI/CD pipelines set up for CDN publishing
- [x] Setup of Github templates (issue templates, PR templates, etc)
- [x] Addition of Apache 2.0 license
- [x] Setup of linting/husky
- [x] Setup of testing framework
- [x] Setup of automerge workflow between release branches and main
- [x] Setup of example component structure
- [ ] Setup of feature flag functionality
- [x] Setup DCO workflow
- [ ] Setup storybook docs tab (README, properties table, CDN, etc)
- [x] CI check workflow
- [ ] Add release schedule
- [ ] https://github.com/carbon-design-system/carbon-for-ai/issues/12
- [x] Add eslint configuration
- [x] convert project to use TS
- [ ] Create React wrappers with @lit/react package
- [ ] Convert to monorepo
```

**Comment by annawen1** [comment]
canary CDN up - ie. https://1.www.s81c.com/common/carbon/ai/tag/v1/canary/extended-button.js and v0.0.1-alpha.0 of the package published on npm!
